fpgasynth:  xilinx:   Pass some ghdl args (work, std) down to gw and xi vendor tools   Removed -abc9 from xilinx default flags (fails sometimes).      Should have way of re-adding, though.  Not sure if it's better.   Pass one file at a time to Vivado (it chokes if there are too many)   Don't generate .bin file for non-zynq parts   Force overwrite of .bin file when generated  generic:   Search for $HOME/fpga/lib stuff in libpath; add that dir to libpath   Added -ni to filter out included .v files   Support giving both vhdl and verilog files, sort of.  Needs work, probably.   Fixed raw.json generation failure due to whiteboxes   Use printf instead of echo since it doesn't interpret strings at all  other arch:   Filter gowin part name for apicula   Fixed ice40 package not being passed in any more xc7-pll:   Print freq. deviation as percentage

diff --git a/fpgasynth b/fpgasynth
--- a/fpgasynth
+++ b/fpgasynth
@@ -3,7 +3,7 @@
 set -o posix
 
 # TODO:
-# - support use of vhd2vl instead of ghdl
+# - support use of vhd2vl instead of ghdl (may be worse, but supports generic)
 # - support mixed vhdl/verilog[/systemverilog]
 # - given how bad xilinx/gowin are, maybe look into Lattice Diamond
 # - document just how broken nextpnr-xilinx really is
@@ -56,16 +56,17 @@ schem=
 tr=
 top=
 delay=
-mk_tstrig=$HOME/fpga/lib/mk_testrig.sh
+mk_tstrig=mk_testrig.sh
 doadd=
 keep=
 opref=
 odir=
+ni=
 sysv=
 ysysv=
 defs=()
 use_yosys=
-libpath=()
+libpath=("$HOME/fpga/lib")
 
 addu() {
   local arr e x g out="$1"
@@ -100,6 +101,7 @@ while [ $# -gt 0 ]; do
     -T) tr=y ;;
     -d) delay=y ;;
     -s) sysv=system ;;
+    -ni) ni=y ;;
     -sv) ysysv=-sv ;;
     -L*) sarg; libpath=("${libpath[@]}" "$arg") ;;
     -v) vhdl=y ;;
@@ -128,6 +130,7 @@ flags:
            This excludes some side effects produced by ghdl and vendor tools.
   -D <def> Add parameter definition for reading Verilog
   -L <dir> Add directory to search path for includes, constraints
+  -ni      Remove Verilog-included files from list (simple match)
   -v       All input files are VHDL instead of Verilog
   -V .. -- Same as -v, but add .. to ghdl argument list
   -s       All input files are System Verilog not supported w/o yosys plugin
@@ -155,8 +158,7 @@ Any option -<x> <parm> can be given as -<x><parm> as well.
 Default ghdl/VHDL args are --std=08 --ieee=synopsys
 
 For ice40 and ecp5, use the nextpnr argument for the device.  If no -- is
-prepended, it is automatically added.  The only package supported for ecp5
-is CABGA381.
+prepended, it is automatically added.  Package is appended with trailing /.
 
 If a gowin device doesn't start with G, it's assumed to be a number,
 optionally followed by a k or K.  This is converted into GW1NSR-LV4CQN48PC7/I6
@@ -202,6 +204,7 @@ f=()
 vf=() # includes .sv files for now
 vhdf=()
 for x; do
+  test -n "$ni" && fgrep '`include "'"${x##*/}\"" "$@" >/dev/null && continue
   case "$x" in /*) ;; *) x="$wd/$x";; esac
   f=("${f[@]}" "$x")
   case "$x" in
@@ -242,11 +245,11 @@ if [ -n "$vhdl" ]; then
  docmd ghdl -i "${vhdl_args[@]}" "${vhdf[@]}" || exit $?
 # docmd ghdl -a "${vhdl_args[@]}"  $(sed -n -e 's/^file \. "\([^"]*\)".*/\1/;T;p' work-obj??.cf | tac)
  cmd="ghdl --latches ${vhdl_args[*]} $* -e $top"  # FIXME:  quote properly
- top=
-else
+fi
+if [ -n "$vf" ]; then
  # should I support -vlog95/-vlog2k?  maybe also other options, like -D?
  # should I support pre-run verification w/ iverilog for better error msgs?
- cmd="read_${sysv}verilog ${ysysv} ${libpatha[*]/#/-I} ${sysv:+${defargs[*]}} $*"  # FIXME:  quote properly
+ cmd="read_${sysv}verilog ${ysysv} ${libpatha[*]/#/-I} ${sysv:+${defargs[*]}} ${vf[*]}"  # FIXME:  quote properly
 fi
 do_yosys() {
 (
@@ -261,13 +264,23 @@ do_yosys() {
       # xilinx proc before coarse (+ a ton of other crap), flatten only w/ -flatten
       # I suppose adding proc; flatten here wouldn't hurt
       echo "synth_${arch[0]} -run :coarse ${top:+-top $top}; proc; flatten; proc;;;"
+      # proc doesn't catch somme whiteboxes (at least ecp5, xilinx), which
+      # should really be ignored anyway, since we're not using yosys for
+      # simulation.
+      # I'd like to drop it, but raw.json is used to obtain info on "top"
+      # If only there were a way to pass -nowb into the synth command..
+      case "${arch[0]}" in
+        ecp5) echo "read_verilog -nowb -lib -specify +/ecp5/cells_sim.v +/ecp5/cells_bb.v" ;;
+        xilinx) echo "read_verilog -nowb -lib -specify +/xilinx/cells_sim.v +/xilinx/cells_xtra.v" ;;
+        gowin) echo "read_verilog -nowb -specify -lib +/gowin/cells_sim.v" ;;
+        ice40) echo "read_verilog -nowb -D ICE40_HX -lib -specify +/ice40/cells_sim.v" ;;
+      esac
     else
       echo "prep -flatten ${top:+-top $top};;;"
     fi
     # ecp5 leaves processes in what should be blackbox modules
-    # I have no idea how to fix this, so just drop it.
-    # Actually, so does Xilinx now.  May as well forget it.
-    #test ecp5 = "${arch[*]}" || echo "write_json ${opref}raw.json"
+    # so does xilinx
+    echo "write_json ${opref}raw.json"
     if [ -n "$doadd" ]; then
       echo "techmap; opt -full; extract_fa;;;"
       echo write_json ${opref}fa.json
@@ -279,7 +292,7 @@ do_yosys() {
     test -n "$pop" && echo $pop; pop="design -load raw"
     case $a in
       ice40) sopt=-dsp ;;
-      xilinx) sopt=-flatten\ -abc9 ;;
+      xilinx) sopt=-flatten ;; # -abc9 fails sometimes
       *) sopt= ;;
     esac
     echo synth_$a ${sopt} ${top:+-top $top}
@@ -292,16 +305,17 @@ for x in "${arch[@]}"; do
   rm -f {pnr,}$x.{png,svg,json} $x.{bin,cfg,svf,asc,sdf}
 done
 do_yosys init
-test -n "$schem" && docmd json2png ${opref}raw
+test -n "$schem" && docmd json2png ${opref}raw.json
 
 # the default test rig bombs on extract_fa, so do it before adding the rig
 if [ -n "$doadd" ]; then
   cmd="read_json alu.json"
-  docmd -o alu.json jq -f $HOME/fpga/lib/fa2add.jq fa.json
+  for lib in "${libpath[@]}"; do test -f "$lib"/fa2add.jq && break; done
+  docmd -o alu.json jq -f "$lib"/fa2add.jq fa.json
 fi
 
 # If the number of inputs/outputs is too large, reduce pin usage by
-# using a serial access method, implemented by ~/fpga/lib/testrig.v and the
+# using a serial access method, implemented by testrig.v and the
 # mainline constructed below.
 # Uses jq to extract data from one of the synth outputs, assuming that the
 # synth outputs will all return the same set of inputs/outputs.
@@ -309,22 +323,32 @@ fi
 # Extract top module from JSON
 topmod="$(jq -c < ${opref}raw.json '.modules|to_entries|
    map(select(.value.attributes.top > 0))|.[]')"
-xtop="$(echo "$topmod" | jq -r .key)"
+xtop="$(printf %s "$topmod" | jq -r .key)"
 test -n "$xtop" && top="$xtop"
 echo "Top: $top"
 # Extract its port list
-ports="$(echo "$topmod" | jq -c '.value.ports|to_entries|
+ports="$(printf %s "$topmod" | jq -c '.value.ports|to_entries|
    map(select(.value.direction=="input" or .value.direction=="output"))|
    map({direction:.value.direction,name:.key,bits:(.value.bits|length)})')"
 # Count ports
 input=0; output=0
-eval $(echo "$ports" | jq -r 'group_by(.direction)|
+eval $(printf %s "$ports" | jq -r 'group_by(.direction)|
      map({direction:.[0].direction,bits:map(.bits)|add})|.[]|
     .direction+"="+(.bits|tostring)')
 # Force use of test rig if # of ports is high, regardless of -T option
 # Then again, Tang Primer has a BG256 package w/ very few unused pins
-# test $((input+output)) -gt 30 && tr=y
-test -n "$tr" && . "$mk_tstrig"
+# Gowin: QN88(9): 70; QN48(1/4/Z): 40/41 PG256(4+): 207 LQ144(all):116-120
+#        MG64: 55 (4SR) PG484: 319 (GW2A) UG484: even more
+# ice40-UltraPlus: sg48: 39
+# ecp5: cabga381: 197-205 cabga756(85k): 365
+# nexus: ??? not really well supported/tested
+# xilinx: clg400(z): 100 ffg676(k): 400
+# test $((input+output)) -gt 39 && tr=y
+if [ -n "$tr" -a ! -f "$mk_tstrig" ]; then
+  for lib in "${libpath[@]}"; do test -f "$lib/$mk_tstrig" && break; done
+  mk_tstrig="$lib/$mk_tstrig"
+fi
+test -n "$tr" -a -f "$mk_tstrig" && . "$mk_tstrig"
 for a in "${arch[@]}"; do
   case "$a" in
     gowin|xilinx) ;;
@@ -450,6 +474,23 @@ for a in "${arch[@]}"; do
 	         *) echo "add_file {$x}" ;;
 	       esac
 	    done
+	    for va in "${vhdl_args[@]}"; do
+	      case "$va" in
+	        --work=*) for x in "${vhdf[@]}"; do
+		            # hack: skip top-level at least
+			    # otherwise gives "not yet analyzed" error
+			    # I need some way of filtering, I guess.
+			    # maybe there's a better way around it
+			    # I should at least get this from the ghdl .cf file
+		            test "${top}.vhd" = "${x##*/}" && continue
+		            echo "set_file_prop -lib {${va#--work=}} {$x}"
+			  done
+#			  echo "set_option -top_module {${va#--work=}.$top}"
+			  ;;
+		--std=93) echo "set_option -vhdl_std vhd1993" ;;
+		--std=08) echo "set_option -vhdl_std vhd2008" ;;
+	      esac
+	    done
 	    test -n "$cst" && echo "add_file {$cst}"
 	    test -n "$sdc" && echo "add_file {$sdc}"
 	    echo "run all"
@@ -470,6 +511,9 @@ for a in "${arch[@]}"; do
 	  continue
 	fi
         #######################
+	d="${d/R-/-}" # stupid nextpnr-gowin/apicula
+	d="${d/PC/C}" # stupid nextpnr-gowin/apicula
+	d="${d/CQN/QN}" # stupid nextpnr-gowin/apicula
 	docmd "${cmd[@]}" --device "$d" ${cst:+--cst} ${cst} || break
 	of="${cst%.cst}"; of="${of##*/}"; of="${of:-$a}"
 	of="${do}${of#$do}"
@@ -496,7 +540,7 @@ for a in "${arch[@]}"; do
 	pcf="$(find_extra pcf $a{,-{"$d#--"{,"$pkg"}}})"
 	of="${pcf%.pcf}"; of="${of##*/}"; of="${of:-$a}"
 	of="${do}${of#$do}"
-	docmd "${cmd[@]}" --asc "${of}.asc" "$d" --package "$p" ${pcf:+--pcf "$pcf"} || break
+	docmd "${cmd[@]}" --asc "${of}.asc" "$d" --package "$pkg" ${pcf:+--pcf "$pcf"} || break
 	docmd icepack "${of}.asc" "${of}.bit"
       done
       # openFPGALoader ...
@@ -603,15 +647,26 @@ for a in "${arch[@]}"; do
           #. /opt/Xilinx/Vivado/2022.2/settings64.sh
 	  # Note: use of ${.../../..&..} is a bashism.  I'm already using bash, so whatever.
 	  #       behavior of ${a[*]/...} is probably bash-specific as well.
+#	  tf=("${vf[@]/#/read_verilog }" "${vhdf[@]/#/read_vhdl }")
+          v2k=-vhdl2008
+	  vl=
+	  for va in "${vhdl_args[@]}"; do
+	    case "$va" in
+	      --work=*) vl="-lib {${va#--work=}}" ;;
+	      --std=93) v2k= ;;
+	      --std=08) v2k=-vhdl2008 ;;
+	    esac
+	  done
           cat >build.tcl <<EOF
             create_project -in_memory -part $rd
-	    # FIXME: quote names
-            ${vf:+read_verilog -sv ${vf[*]}}
-	    ${vhdf:+read_vhdl ${vhdf[*]}}
-            ${xdc:+read_xdc $xdc}
-            ${sdc:+read_xdc $sdc}
+	    ${vf[*]/*/read_verilog {&\}
+            }
+            ${vhdf[*]/*/read_vhdl $v2k $vl {&\}
+            }
+            ${xdc:+read_xdc {$xdc\}}
+            ${sdc:+read_xdc {$sdc\}}
 
-            synth_design ${defs[*]/*/-verilog_define \{&\}} -top $top -part $rd -include_dirs {{$wd}${libpatha:+ }${libpatha[*]/*/\{&\}}}
+            synth_design ${defs[*]/*/-verilog_define {&\}} -top $top -part $rd -include_dirs {{$wd}${libpatha:+ }${libpatha[*]/*/{&\}}}
             report_timing_summary -file synth_timing_summary.rpt
             report_power -file synth_power.rpt
             write_checkpoint -force synthesis
@@ -624,6 +679,8 @@ for a in "${arch[@]}"; do
             # I cheat on one of the MMCMs:  1207 VCO w/ max 1200
             # If there is a way to turn it into a warning, I can't find the docs
             set_property IS_ENABLED FALSE [get_drc_checks PDRC-34]
+	    # I guess if there are too many unconstrained I/O, it fails.
+	    set_property IS_ENABLED FALSE [get_drc_checks UCIO-1]
             route_design
             # !!!!!!!!!!!!!!!!!!! Crash !!!!!!!!!!!!!!!!!!!!!!!!!!!!
             # Either a seg fault or:
@@ -696,8 +753,9 @@ EOF
 	docmd "$f2b" --part_file "$dbd/$rd/part.yaml" --part_name "${d%-*}" \
 	             --frm_file "${of}.frames" --output_file "${of}.bit"
       done
+      test zynq7 = "$fam" || continue
       echo "all: { ${of}.bit }" >"${of}.bif"
-      docmd bootgen -arch zynq -image "${of}.bif" -process_bitstream bin
+      docmd bootgen -w on -arch zynq -image "${of}.bif" -process_bitstream bin
       if false; then
       # FIXME:  Add bootgen support
       (
@@ -747,7 +805,7 @@ EOF
         #                   16-bit Non-secure 0x00000001 16-bit width
         # smc.direct_cmd     Both  Non-secure 0x02400000 Select ModeReg and UpdateRegs
       ) >ebaz.int
-      docmd bootgen -arch zynq -image boot.bif -o boot.bin
+      docmd bootgen -w on -arch zynq -image boot.bif -o boot.bin
       fi
       ;;
   esac
